import json
from datetime import datetime

def fetch_data():
    now = datetime.utcnow().strftime("%Y-%m-%d %H:%M")
    
    # 30 heroes structured data for Patch 7.41+ with winrate_4k
    meta_heroes = [
        {
            "name": "Shadow Fiend",
            "role": "Mid",
            "winrate_d2pt": "54.2%",
            "winrate_4k": "51.8%",
            "pickrate_d2pt": "15%",
            "banrate_pro": "42%",
            "tier": "S",
            "innate_ability": "Necromastery (души дают урон и баффают способности в патче 7.41+)",
            "core_items": ["black_king_bar", "blink", "ultimate_scepter", "silver_edge"],
            "best_with": ["magnataur", "enigma", "tidehunter"],
            "counters": ["templar_assassin", "pudge", "viper"],
            "laning_winrate": "53.5%",
            "versatility": "4.2",
            "damage_ratio": { "phys": 55, "mag": 45, "pure": 0 },
            "power_spike": "Мидгейм (15-25 мин)"
        },
        {
            "name": "Tiny",
            "role": "Mid",
            "winrate_d2pt": "55.4%",
            "winrate_4k": "52.1%",
            "pickrate_d2pt": "18%",
            "banrate_pro": "65%",
            "tier": "S",
            "innate_ability": "Craggy Exterior (пассивная броня и урон по площади при атаках)",
            "core_items": ["blink", "power_treads", "black_king_bar", "echo_sabre"],
            "best_with": ["rubick", "wisp", "nevermore"],
            "counters": ["lifestealer", "necrolyte", "viper"],
            "laning_winrate": "55.0%",
            "versatility": "6.5",
            "damage_ratio": { "phys": 70, "mag": 30, "pure": 0 },
            "power_spike": "Ранняя агрессия (10-20 мин)"
        },
        {
            "name": "Zeus",
            "role": "Mid",
            "winrate_d2pt": "53.1%",
            "winrate_4k": "54.5%",
            "pickrate_d2pt": "12%",
            "banrate_pro": "35%",
            "tier": "S",
            "innate_ability": "Static Field (каждое заклинание наносит процентный урон от текущего здоровья)",
            "core_items": ["arcane_boots", "phylactery", "ultimate_scepter", "refresher"],
            "best_with": ["treant", "crystal_maiden", "bloodseeker"],
            "counters": ["antimage", "viper", "pudge"],
            "laning_winrate": "51.2%",
            "versatility": "3.0",
            "damage_ratio": { "phys": 0, "mag": 100, "pure": 0 },
            "power_spike": "Лейтгейм (35+ мин)"
        },
        {
            "name": "Dawnbreaker",
            "role": "Offlane",
            "winrate_d2pt": "52.3%",
            "winrate_4k": "51.2%",
            "pickrate_d2pt": "10%",
            "banrate_pro": "28%",
            "tier": "A",
            "innate_ability": "Landmower (каждая 4-я атака исцеляет союзников вокруг)",
            "core_items": ["phase_boots", "echo_sabre", "black_king_bar", "heavens_halberd"],
            "best_with": ["wisp", "nevermore", "storm_spirit"],
            "counters": ["enigma", "silencer", "pudge"],
            "laning_winrate": "54.0%",
            "versatility": "5.0",
            "damage_ratio": { "phys": 80, "mag": 20, "pure": 0 },
            "power_spike": "Мидгейм (15-25 мин)"
        },
        {
            "name": "Marci",
            "role": "Support",
            "winrate_d2pt": "51.8%",
            "winrate_4k": "49.5%",
            "pickrate_d2pt": "11%",
            "banrate_pro": "30%",
            "tier": "A",
            "innate_ability": "Special Delivery (увеличенная дальность передачи предметов курьерами и бафф союзников)",
            "core_items": ["phase_boots", "black_king_bar", "basher", "blink"],
            "best_with": ["wisp", "magnataur", "nevermore"],
            "counters": ["winter_wyvern", "pudge", "beastmaster"],
            "laning_winrate": "52.1%",
            "versatility": "7.2",
            "damage_ratio": { "phys": 90, "mag": 10, "pure": 0 },
            "power_spike": "Мидгейм (20-30 мин)"
        },
        {
            "name": "Winter Wyvern",
            "role": "Support",
            "winrate_d2pt": "52.5%",
            "winrate_4k": "50.1%",
            "pickrate_d2pt": "9%",
            "banrate_pro": "40%",
            "tier": "A",
            "innate_ability": "Cold Embrace (усиленное исцеление и защита от физического урона)",
            "core_items": ["arcane_boots", "glimmer_cape", "force_staff", "ultimate_scepter"],
            "best_with": ["nevermore", "magnataur", "faceless_void"],
            "counters": ["ancient_apparition", "rubick", "doom_bringer"],
            "laning_winrate": "50.5%",
            "versatility": "5.5",
            "damage_ratio": { "phys": 10, "mag": 90, "pure": 0 },
            "power_spike": "Лейтгейм (30+ мин)"
        },
        {
            "name": "Nature's Prophet",
            "role": "Support",
            "winrate_d2pt": "51.2%",
            "winrate_4k": "48.9%",
            "pickrate_d2pt": "14%",
            "banrate_pro": "55%",
            "tier": "S",
            "innate_ability": "Spirit of the Forest (увеличение урона за каждое живое дерево на карте)",
            "core_items": ["urn_of_shadows", "solar_crest", "orchid", "force_staff"],
            "best_with": ["tinker", "spirit_breaker", "bounty_hunter"],
            "counters": ["timbersaw", "lina", "nevermore"],
            "laning_winrate": "53.2%",
            "versatility": "8.0",
            "damage_ratio": { "phys": 60, "mag": 40, "pure": 0 },
            "power_spike": "Ранняя игра (5-15 мин)"
        },
        {
            "name": "Invoker",
            "role": "Mid",
            "winrate_d2pt": "53.6%",
            "winrate_4k": "50.5%",
            "pickrate_d2pt": "13%",
            "banrate_pro": "45%",
            "tier": "S",
            "innate_ability": "Mastermind (сферы дают пассивный реген, скорость и урон от заклинаний)",
            "core_items": ["travel_boots", "blink", "black_king_bar", "shivas_guard"],
            "best_with": ["faceless_void", "magnataur", "tidehunter"],
            "counters": ["antimage", "templar_assassin", "doom_bringer"],
            "laning_winrate": "52.0%",
            "versatility": "4.5",
            "damage_ratio": { "phys": 20, "mag": 80, "pure": 0 },
            "power_spike": "Мидгейм (20-30 мин)"
        },
        {
            "name": "Axe",
            "role": "Offlane",
            "winrate_d2pt": "52.3%",
            "winrate_4k": "53.2%",
            "pickrate_d2pt": "11%",
            "banrate_pro": "38%",
            "tier": "S",
            "innate_ability": "Spin To Win (увеличенный шанс срабатывания Counter Helix против нескольких целей)",
            "core_items": ["blink", "blade_mail", "black_king_bar", "shivas_guard"],
            "best_with": ["invoker", "dazzle", "oracle"],
            "counters": ["viper", "necrolyte", "venomancer"],
            "laning_winrate": "51.8%",
            "versatility": "4.0",
            "damage_ratio": { "phys": 40, "mag": 0, "pure": 60 },
            "power_spike": "Ранняя игра (12-22 мин)"
        },
        {
            "name": "Clinkz",
            "role": "Carry",
            "winrate_d2pt": "56.0%",
            "winrate_4k": "52.8%",
            "pickrate_d2pt": "8%",
            "banrate_pro": "32%",
            "tier": "A",
            "innate_ability": "Bone Summoning (при смерти крипов призываются скелеты-лучники)",
            "core_items": ["power_treads", "desolator", "orchid", "black_king_bar"],
            "best_with": ["chen", "enchantress", "bounty_hunter"],
            "counters": ["slardar", "dust", "spirit_breaker"],
            "laning_winrate": "54.5%",
            "versatility": "3.5",
            "damage_ratio": { "phys": 85, "mag": 15, "pure": 0 },
            "power_spike": "Мидгейм (15-25 мин)"
        },
        {
            "name": "Elder Titan",
            "role": "Support",
            "winrate_d2pt": "54.2%",
            "winrate_4k": "51.0%",
            "pickrate_d2pt": "7%",
            "banrate_pro": "29%",
            "tier": "A",
            "innate_ability": "Natural Order (пассивное снижение базовой брони и сопротивления магии)",
            "core_items": ["arcane_boots", "glimmer_cape", "force_staff", "shivas_guard"],
            "best_with": ["magnataur", "faceless_void", "nevermore"],
            "counters": ["lina", "templar_assassin", "sniper"],
            "laning_winrate": "49.8%",
            "versatility": "6.0",
            "damage_ratio": { "phys": 50, "mag": 50, "pure": 0 },
            "power_spike": "Лейтгейм (30+ мин)"
        },
        {
            "name": "Centaur Warrunner",
            "role": "Offlane",
            "winrate_d2pt": "51.9%",
            "winrate_4k": "52.5%",
            "pickrate_d2pt": "12%",
            "banrate_pro": "35%",
            "tier": "A",
            "innate_ability": "Rawhide (пассивный бонус к максимальному здоровью за каждого задетого способностями врага)",
            "core_items": ["phase_boots", "blink", "blade_mail", "crimson_guard"],
            "best_with": ["nevermore", "crystal_maiden", "phoenix"],
            "counters": ["lifestealer", "necrolyte", "viper"],
            "laning_winrate": "53.0%",
            "versatility": "4.8",
            "damage_ratio": { "phys": 45, "mag": 55, "pure": 0 },
            "power_spike": "Мидгейм (15-25 мин)"
        },
        {
            "name": "Rubick",
            "role": "Support",
            "winrate_d2pt": "50.8%",
            "winrate_4k": "48.2%",
            "pickrate_d2pt": "16%",
            "banrate_pro": "42%",
            "tier": "A",
            "innate_ability": "Might and Steal (увеличение урона и длительности украденных заклинаний)",
            "core_items": ["arcane_boots", "blink", "lens", "force_staff"],
            "best_with": ["nevermore", "faceless_void", "tidehunter"],
            "counters": ["slark", "clinkz", "riki"],
            "laning_winrate": "49.2%",
            "versatility": "9.0",
            "damage_ratio": { "phys": 10, "mag": 90, "pure": 0 },
            "power_spike": "Мидгейм (20-30 мин)"
        },
        {
            "name": "Storm Spirit",
            "role": "Mid",
            "winrate_d2pt": "52.4%",
            "winrate_4k": "51.2%",
            "pickrate_d2pt": "11%",
            "banrate_pro": "37%",
            "tier": "A",
            "innate_ability": "Galvanized (восстановление маны при убийствах врагов в радиусе)",
            "core_items": ["power_treads", "orchid", "black_king_bar", "bloodstone"],
            "best_with": ["lifestealer", "io", "nevermore"],
            "counters": ["antimage", "silencer", "doom_bringer"],
            "laning_winrate": "51.0%",
            "versatility": "4.0",
            "damage_ratio": { "phys": 15, "mag": 85, "pure": 0 },
            "power_spike": "Мидгейм (18-28 мин)"
        },
        {
            "name": "Tidehunter",
            "role": "Offlane",
            "winrate_d2pt": "50.1%",
            "winrate_4k": "50.8%",
            "pickrate_d2pt": "10%",
            "banrate_pro": "31%",
            "tier": "B",
            "innate_ability": "Kraken Shell (снятие дебаффов при получении определенного объема урона)",
            "core_items": ["phase_boots", "blink", "pipe_of_insight", "guardian_greaves"],
            "best_with": ["nevermore", "invoker", "rubick"],
            "counters": ["slark", "ursa", "viper"],
            "laning_winrate": "52.5%",
            "versatility": "4.2",
            "damage_ratio": { "phys": 50, "mag": 50, "pure": 0 },
            "power_spike": "Мидгейм (15-25 мин)"
        },
        {
            "name": "Razor",
            "role": "Carry",
            "winrate_d2pt": "52.8%",
            "winrate_4k": "51.0%",
            "pickrate_d2pt": "9%",
            "banrate_pro": "28%",
            "tier": "A",
            "innate_ability": "Unstable Current (пассивный бонус к скорости передвижения и периодический удар током по врагам)",
            "core_items": ["power_treads", "black_king_bar", "shivas_guard", "refresher"],
            "best_with": ["io", "omniknight", "oracle"],
            "counters": ["sniper", "viper", "lina"],
            "laning_winrate": "53.8%",
            "versatility": "5.0",
            "damage_ratio": { "phys": 60, "mag": 40, "pure": 0 },
            "power_spike": "Мидгейм (15-25 мин)"
        },
        {
            "name": "Timbersaw",
            "role": "Offlane",
            "winrate_d2pt": "53.2%",
            "winrate_4k": "51.5%",
            "pickrate_d2pt": "11%",
            "banrate_pro": "45%",
            "tier": "S",
            "innate_ability": "Reactive Armor (накапливаемая броня и реген здоровья при получении физических атак)",
            "core_items": ["arcane_boots", "shivas_guard", "black_king_bar", "bloodstone"],
            "best_with": ["keeper_of_the_light", "io", "nevermore"],
            "counters": ["viper", "necrolyte", "doom_bringer"],
            "laning_winrate": "54.2%",
            "versatility": "4.0",
            "damage_ratio": { "phys": 10, "mag": 10, "pure": 80 },
            "power_spike": "Ранняя игра (12-22 мин)"
        },
        {
            "name": "Pangolier",
            "role": "Mid",
            "winrate_d2pt": "51.1%",
            "winrate_4k": "47.8%",
            "pickrate_d2pt": "12%",
            "banrate_pro": "41%",
            "tier": "B",
            "innate_ability": "Shield Crash (бонусное сопротивление эффектам во время каста ультимейта)",
            "core_items": ["arcane_boots", "diffusal_blade", "blink", "shivas_guard"],
            "best_with": ["bloodseeker", "nevermore", "lich"],
            "counters": ["doom_bringer", "silencer", "bloodseeker"],
            "laning_winrate": "49.5%",
            "versatility": "4.5",
            "damage_ratio": { "phys": 40, "mag": 60, "pure": 0 },
            "power_spike": "Мидгейм (15-25 мин)"
        },
        {
            "name": "Windranger",
            "role": "Carry",
            "winrate_d2pt": "52.0%",
            "winrate_4k": "50.9%",
            "pickrate_d2pt": "13%",
            "banrate_pro": "38%",
            "tier": "A",
            "innate_ability": "Focus Fire (увеличивает скорость атаки на 500 по одной цели)",
            "core_items": ["maelstrom", "black_king_bar", "monkey_king_bar", "blink"],
            "best_with": ["nevermore", "magnataur", "crystal_maiden"],
            "counters": ["axe", "blade_mail", "centaur"],
            "laning_winrate": "52.8%",
            "versatility": "6.0",
            "damage_ratio": { "phys": 50, "mag": 50, "pure": 0 },
            "power_spike": "Мидгейм (20-30 мин)"
        },
        {
            "name": "Earth Spirit",
            "role": "Support",
            "winrate_d2pt": "50.9%",
            "winrate_4k": "48.5%",
            "pickrate_d2pt": "8%",
            "banrate_pro": "25%",
            "tier": "A",
            "innate_ability": "Stone Reserves (пассивный реген каменных копий раз в 15 секунд)",
            "core_items": ["urn_of_shadows", "blink", "force_staff", "black_king_bar"],
            "best_with": ["nevermore", "storm_spirit", "invoker"],
            "counters": ["silencer", "death_prophet", "bloodseeker"],
            "laning_winrate": "51.0%",
            "versatility": "7.5",
            "damage_ratio": { "phys": 10, "mag": 90, "pure": 0 },
            "power_spike": "Ранняя игра (8-18 мин)"
        },
        {
            "name": "Magnus",
            "role": "Offlane",
            "winrate_d2pt": "51.5%",
            "winrate_4k": "49.9%",
            "pickrate_d2pt": "10%",
            "banrate_pro": "36%",
            "tier": "A",
            "innate_ability": "Empower (пассивный клив и бонус к урону для союзников ближнего боя)",
            "core_items": ["blink", "force_staff", "black_king_bar", "refresher"],
            "best_with": ["nevermore", "phantom_assassin", "juggernaut"],
            "counters": ["rubick", "winter_wyvern", "doom_bringer"],
            "laning_winrate": "50.8%",
            "versatility": "5.5",
            "damage_ratio": { "phys": 40, "mag": 60, "pure": 0 },
            "power_spike": "Мидгейм (15-25 мин)"
        },
        {
            "name": "Lina",
            "role": "Carry",
            "winrate_d2pt": "53.5%",
            "winrate_4k": "51.2%",
            "pickrate_d2pt": "12%",
            "banrate_pro": "44%",
            "tier": "S",
            "innate_ability": "Fiery Soul (пассивный буст скорости атаки и передвижения при касте заклинаний)",
            "core_items": ["travel_boots", "maelstrom", "black_king_bar", "satanic"],
            "best_with": ["crystal_maiden", "shadow_demon", "bane"],
            "counters": ["nyx_assassin", "antimage", "blademail"],
            "laning_winrate": "54.8%",
            "versatility": "5.0",
            "damage_ratio": { "phys": 50, "mag": 50, "pure": 0 },
            "power_spike": "Лейтгейм (25-35 мин)"
        },
        {
            "name": "Puck",
            "role": "Mid",
            "winrate_d2pt": "52.1%",
            "winrate_4k": "49.0%",
            "pickrate_d2pt": "14%",
            "banrate_pro": "39%",
            "tier": "A",
            "innate_ability": "Puckish (восстановление здоровья и маны при уклонении от вражеских атак)",
            "core_items": ["witch_blade", "blink", "cyclone", "dagon_5"],
            "best_with": ["nevermore", "faceless_void", "tidehunter"],
            "counters": ["doom_bringer", "silencer", "night_stalker"],
            "laning_winrate": "51.5%",
            "versatility": "4.2",
            "damage_ratio": { "phys": 15, "mag": 85, "pure": 0 },
            "power_spike": "Мидгейм (15-25 мин)"
        },
        {
            "name": "Ember Spirit",
            "role": "Mid",
            "winrate_d2pt": "51.8%",
            "winrate_4k": "49.8%",
            "pickrate_d2pt": "11%",
            "banrate_pro": "35%",
            "tier": "A",
            "innate_ability": "Immolation (постоянный огненный урон всем врагам вокруг)",
            "core_items": ["phase_boots", "maelstrom", "shivas_guard", "black_king_bar"],
            "best_with": ["nevermore", "magnataur", "crystal_maiden"],
            "counters": ["doom_bringer", "silencer", "shadow_shaman"],
            "laning_winrate": "50.2%",
            "versatility": "4.0",
            "damage_ratio": { "phys": 40, "mag": 60, "pure": 0 },
            "power_spike": "Мидгейм (15-25 min)"
        },
        {
            "name": "Templar Assassin",
            "role": "Carry",
            "winrate_d2pt": "52.6%",
            "winrate_4k": "50.2%",
            "pickrate_d2pt": "9%",
            "banrate_pro": "33%",
            "tier": "A",
            "innate_ability": "Meld Strike (дополнительный физический урон и снижение брони при атаке из инвиза)",
            "core_items": ["power_treads", "blink", "desolator", "black_king_bar"],
            "best_with": ["nevermore", "magnataur", "dazzle"],
            "counters": ["batrider", "venomancer", "viper"],
            "laning_winrate": "53.0%",
            "versatility": "3.5",
            "damage_ratio": { "phys": 95, "mag": 5, "pure": 0 },
            "power_spike": "Мидгейм (18-28 мин)"
        },
        {
            "name": "Pudge",
            "role": "Offlane",
            "winrate_d2pt": "50.5%",
            "winrate_4k": "51.9%",
            "pickrate_d2pt": "15%",
            "banrate_pro": "20%",
            "tier": "B",
            "innate_ability": "Flesh Heap (постоянный прирост силы за каждого умершего рядом врага)",
            "core_items": ["blink", "blade_mail", "hood_of_defiance", "shivas_guard"],
            "best_with": ["rubick", "nevermore", "techies"],
            "counters": ["lifestealer", "ursa", "timbersaw"],
            "laning_winrate": "48.5%",
            "versatility": "7.0",
            "damage_ratio": { "phys": 10, "mag": 50, "pure": 40 },
            "power_spike": "Мидгейм (15-25 мин)"
        },
        {
            "name": "Viper",
            "role": "Mid",
            "winrate_d2pt": "51.0%",
            "winrate_4k": "52.3%",
            "pickrate_d2pt": "8%",
            "banrate_pro": "28%",
            "tier": "B",
            "innate_ability": "Corrosive Skin (пассивный периодический урон, замедление и маг-резист при получении урона)",
            "core_items": ["power_treads", "black_king_bar", "ultimate_scepter", "hurricane_pike"],
            "best_with": ["nevermore", "omniknight", "oracle"],
            "counters": ["lina", "sniper", "broodmother"],
            "laning_winrate": "55.5%",
            "versatility": "3.0",
            "damage_ratio": { "phys": 10, "mag": 90, "pure": 0 },
            "power_spike": "Ранняя игра (10-20 мин)"
        },
        {
            "name": "Doom",
            "role": "Offlane",
            "winrate_d2pt": "51.2%",
            "winrate_4k": "49.5%",
            "pickrate_d2pt": "10%",
            "banrate_pro": "48%",
            "tier": "S",
            "innate_ability": "Devour (пассивное поглощение лесных крипов с получением их способностей и золота)",
            "core_items": ["shivas_guard", "blink", "black_king_bar", "refresher"],
            "best_with": ["nevermore", "crystal_maiden", "phoenix"],
            "counters": ["linkens_sphere", "wraith_king", "medusa"],
            "laning_winrate": "49.0%",
            "versatility": "5.0",
            "damage_ratio": { "phys": 20, "mag": 20, "pure": 60 },
            "power_spike": "Мидгейм (20-30 мин)"
        },
        {
            "name": "Faceless Void",
            "role": "Carry",
            "winrate_d2pt": "51.7%",
            "winrate_4k": "50.1%",
            "pickrate_d2pt": "12%",
            "banrate_pro": "35%",
            "tier": "A",
            "innate_ability": "Chronosphere Walk (постоянная возможность передвигаться внутри чужих Хроносфер)",
            "core_items": ["power_treads", "maelstrom", "black_king_bar", "butterfly"],
            "best_with": ["invoker", "nevermore", "witch_doctor"],
            "counters": ["shadow_demon", "wraith_king", "pudge"],
            "laning_winrate": "50.5%",
            "versatility": "3.0",
            "damage_ratio": { "phys": 85, "mag": 15, "pure": 0 },
            "power_spike": "Лейтгейм (30+ мин)"
        },
        {
            "name": "Hoodwink",
            "role": "Support",
            "winrate_d2pt": "52.4%",
            "winrate_4k": "49.9%",
            "pickrate_d2pt": "14%",
            "banrate_pro": "33%",
            "tier": "A",
            "innate_ability": "Scurry (позволяет пассивно проходить сквозь деревья и увеличивает уклонение рядом с ними)",
            "core_items": ["arcane_boots", "gleipnir", "force_staff", "lens"],
            "best_with": ["nevermore", "storm_spirit", "timbersaw"],
            "counters": ["spirit_breaker", "storm_spirit", "clockwerk"],
            "laning_winrate": "51.5%",
            "versatility": "6.8",
            "damage_ratio": { "phys": 20, "mag": 80, "pure": 0 },
            "power_spike": "Мидгейм (15-25 мин)"
        }
    ],
    "teams": [
        {
            "name": "Team Falcons",
            "power_index": 95,
            "recent_results": "W-W-W-W-L",
            "status": "Тир-1 Фаворит",
            "playstyle": "Быстрый темп и удушение (Fast Tempo / Deathball)",
            "average_match_length": "34:12",
            "win_rate_10m": "84%",
            "coach_strategy": "Сильный упор на контр-инициацию, флекс Магнуса/Рубика на ранних стадиях",
            "key_heroes": ["Razor", "Timbersaw"],
            "last_opponents": ["Spirit: W", "Gaimin: W", "Xtreme: L"]
        },
        {
            "name": "Team Yandex",
            "power_index": 98,
            "recent_results": "W-W-W-W-W",
            "status": "Абсолютный Лидер",
            "playstyle": "Ультра-агрессивный ганк и ранний пуш (Ultra-Aggressive Gank / Early Push)",
            "average_match_length": "32:05",
            "win_rate_10m": "92%",
            "coach_strategy": "Ранний пик Tiny и Zeus, точечный контроль макро-карты",
            "key_heroes": ["Tiny", "Zeus"],
            "last_opponents": ["Spirit: W", "PARIVISION: W", "MOUZ: W"]
        },
        {
            "name": "PARIVISION",
            "power_index": 88,
            "recent_results": "W-W-L-W-W",
            "status": "Тир-1 Претендент",
            "playstyle": "Тяжелый тимфайт и лейт-лейт (Heavy Teamfight / Late-Game Scale)",
            "average_match_length": "38:40",
            "win_rate_10m": "75%",
            "coach_strategy": "Игра вокруг ультимейтов Winter Wyvern и Doom, плотный фарм керри",
            "key_heroes": ["Winter Wyvern", "Doom"],
            "last_opponents": ["Rune Eaters: W", "MOUZ: W", "Spirit: L"]
        },
        {
            "name": "BB Team",
            "power_index": 85,
            "recent_results": "L-W-L-W-W",
            "status": "Тир-1 Претендент",
            "playstyle": "Гибкое разделение карты и сплит-пуш (Flexible Split-push / Map Control)",
            "average_match_length": "36:15",
            "win_rate_10m": "78%",
            "coach_strategy": "Использование active саппортов вроде Earth Spirit для постоянного давления",
            "key_heroes": ["Windranger", "Earth Spirit"],
            "last_opponents": ["LGD: W", "Nigma: W", "Falcons: L"]
        },
        {
            "name": "Team Spirit",
            "power_index": 82,
            "recent_results": "W-W-L-W-L",
            "status": "В стадии перестройки (Спад)",
            "playstyle": "Медленное удушение через камбэк (Slow Control / Late Comeback)",
            "average_match_length": "41:30",
            "win_rate_10m": "68%",
            "coach_strategy": "Создание пространства под фарм Lina, жесткое зонирование через Magnus",
            "key_heroes": ["Magnus", "Lina"],
            "last_opponents": ["Yandex: L", "Liquid: W", "Falcons: L"]
        }
    ]
}

if __name__ == "__main__":
    data = fetch_data()
    with open("data.json", "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
    print("Successfully generated data.json with Legend/Ancient winrates!")

