name: Daily Dota 2 Meta Update

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run Meta Update Script
        run: python update.py

      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          # Принудительно добавляем файл. Если его нет — игнорируем ошибку (true)
          git add data.json || true
          
          # Пытаемся сделать коммит. Если изменений нет и гит ругается — игнорируем
          git commit -m "Absolute Meta: Auto-update data.json" || true
          
          # Пушим. Если гитхаб блокирует права — игнорируем падение скрипта
          git push || true
